baseURL = "/"
languageCode = "en-us"
title = "Marketing Trends"
theme = "hugo-serif-theme"

[params]
#google_analytics_id=""


[[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 1


[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2