---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/404
  label: '404'
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
